version: '3.2'

services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    links:
      - wordpress
    restart: always
    environment:
      CLIENT_MAX_BODY_SIZE: 0
      DOMAINS: '${DOMAIN} -> http://wordpress'
      STAGE: 'production'

  wordpress:
    restart: always
    image: wordpress
    environment:
      WORDPRESS_DB_PASSWORD: S{WORDPRESS_DB_PASSWORD}
    volumes:
    - ./volumes/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: S{WORDPRESS_DB_PASSWORD}
